export const specialties = [
  'Medicina General',
  'Pediatría',
  'Ginecología',
  'Cardiología',
  'Dermatología',
  'Traumatología',
  'Neurología',
  'Psicología',
  'Psiquiatría',
  'Endocrinología',
  'Gastroenterología',
  'Neumología',
  'Otorrinolaringología',
  'Oftalmología',
  'Urología',
  'Reumatología',
  'Oncología',
  'Nutrición',
  'Medicina Interna'
]

export const departments = [
  'Amazonas',
  'Áncash',
  'Apurímac',
  'Arequipa',
  'Ayacucho',
  'Cajamarca',
  'Callao',
  'Cusco',
  'Huancavelica',
  'Huánuco',
  'Ica',
  'Junín',
  'La Libertad',
  'Lambayeque',
  'Lima',
  'Loreto',
  'Madre de Dios',
  'Moquegua',
  'Pasco',
  'Piura',
  'Puno',
  'San Martín',
  'Tacna',
  'Tumbes',
  'Ucayali'
]

export const plans = [
  {
    id: 'basic',
    name: 'Básico',
    price: 'S/ 149',
    visibility: 'Visible en Buscar Doctor.',
    features: ['Presencia en resultados de búsqueda', 'Perfil profesional validable', 'Renovación trimestral']
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 'S/ 249',
    visibility: 'Visible en Buscar Doctor, Orientación IA y Atención Ahora.',
    features: ['Prioridad sobre Básico', 'Recomendable por síntomas', 'Atención inmediata habilitada']
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 'S/ 379',
    visibility: 'Visible en toda la plataforma, incluyendo Inicio y destacados.',
    features: ['Máxima prioridad', 'Carruseles y recomendados', 'Mayor exposición comercial']
  }
]

export const keywordMap = {
  // Síntomas Generales
  fiebre: ['Medicina General', 'Pediatría'],
  tos: ['Neumología', 'Medicina General'],
  gripe: ['Medicina General'],
  dolor: ['Medicina General', 'Traumatología'],
  malestar: ['Medicina General'],
  cansancio: ['Medicina General', 'Endocrinología'],
  mareo: ['Neurología', 'Otorrinolaringología'],
  nauseas: ['Gastroenterología'],
  
  // Cardiología
  pecho: ['Cardiología', 'Neumología'],
  corazon: ['Cardiología'],
  corazón: ['Cardiología'],
  palpitaciones: ['Cardiología'],
  tension: ['Cardiología'],
  presion: ['Cardiología'],
  
  // Dermatología
  piel: ['Dermatología'],
  sarpullido: ['Dermatología'],
  acné: ['Dermatología'],
  granitos: ['Dermatología'],
  manchas: ['Dermatología'],
  picazon: ['Dermatología'],
  comezon: ['Dermatología'],
  
  // Ginecología
  embarazo: ['Ginecología'],
  menstrual: ['Ginecología'],
  ovarios: ['Ginecología'],
  periodo: ['Ginecología'],
  vagina: ['Ginecología'],
  
  // Salud Mental (Psicología / Psiquiatría)
  ansiedad: ['Psicología', 'Psiquiatría'],
  estres: ['Psicología'],
  estrés: ['Psicología'],
  depresion: ['Psiquiatría', 'Psicología'],
  depresión: ['Psiquiatría', 'Psicología'],
  tristeza: ['Psicología'],
  panico: ['Psiquiatría', 'Psicología'],
  insomnio: ['Psiquiatría', 'Neurología'],
  psicopata: ['Psiquiatría', 'Psicología'],
  agresivo: ['Psiquiatría', 'Psicología'],
  loco: ['Psiquiatría'],
  nervios: ['Psicología', 'Psiquiatría'],
  angustia: ['Psicología', 'Psiquiatría'],
  miedo: ['Psicología'],
  fobia: ['Psicología'],
  bipolar: ['Psiquiatría'],
  esquizofrenia: ['Psiquiatría'],
  alucinaciones: ['Psiquiatría'],
  
  // Otros
  hormona: ['Endocrinología'],
  tiroides: ['Endocrinología'],
  estomago: ['Gastroenterología'],
  estómago: ['Gastroenterología'],
  abdomen: ['Gastroenterología'],
  diarrea: ['Gastroenterología'],
  gastritis: ['Gastroenterología'],
  respiracion: ['Neumología'],
  respiración: ['Neumología'],
  pulmon: ['Neumología'],
  oido: ['Otorrinolaringología'],
  oído: ['Otorrinolaringología'],
  garganta: ['Otorrinolaringología'],
  amigdalas: ['Otorrinolaringología'],
  vista: ['Oftalmología'],
  ojos: ['Oftalmología'],
  lentes: ['Oftalmología'],
  riñon: ['Urología'],
  riñón: ['Urología'],
  orina: ['Urología'],
  articulaciones: ['Reumatología'],
  huesos: ['Traumatología'],
  fractura: ['Traumatología'],
  espalda: ['Traumatología'],
  columna: ['Traumatología'],
  cancer: ['Oncología'],
  cáncer: ['Oncología'],
  tumor: ['Oncología'],
  quimio: ['Oncología'],
  nutricion: ['Nutrición'],
  nutrición: ['Nutrición'],
  dieta: ['Nutrición'],
  obesidad: ['Nutrición', 'Endocrinología'],
  niño: ['Pediatría'],
  nino: ['Pediatría'],
  bebe: ['Pediatría'],
  migraña: ['Neurología'],
  migrana: ['Neurología'],
  cabeza: ['Neurología'],
  diabetes: ['Endocrinología'],
  glucosa: ['Endocrinología'],
  azucar: ['Endocrinología'],
  chequeo: ['Medicina Interna', 'Medicina General']
}

const weekdays = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado']

const hours = ['08:00', '09:00', '10:00', '11:00', '16:00', '17:00', '18:00', '19:00']

const baseSchedules = weekdays.reduce((acc, day, index) => {
  acc[day] = hours.filter((_, hourIndex) => (hourIndex + index) % 2 === 0)
  return acc
}, {})

const nowDay = 'Lunes'

export const seedDoctors = [
  {
    id: 'doc-1',
    name: 'Dra. Valeria Mena',
    specialty: 'Dermatología',
    cmp: 'CMP 45921',
    department: 'La Libertad',
    province: 'Trujillo',
    district: 'Víctor Larco',
    clinic: 'Clínica San Pablo Trujillo',
    experience: 12,
    price: 95,
    rating: 4.9,
    plan: 'premium',
    status: 'active',
    image: '/uploads/doctor-01.webp',
    photoPath: '/uploads/doctor-01.webp',
    email: 'vmena@meditrujillo.pe',
    whatsapp: '51987654321',
    availableNow: true,
    attentionNow: true,
    featured: true,
    subscriptionStartedAt: '2026-03-01',
    subscriptionEndsAt: '2026-05-30',
    schedules: baseSchedules
  },
  {
    id: 'doc-2',
    name: 'Dr. José Rodríguez',
    specialty: 'Cardiología',
    cmp: 'CMP 40876',
    department: 'La Libertad',
    province: 'Trujillo',
    district: 'Trujillo',
    clinic: 'Centro Cardiovascular Norte',
    experience: 15,
    price: 120,
    rating: 4.8,
    plan: 'premium',
    status: 'active',
    image: '/uploads/doctor-02.webp',
    photoPath: '/uploads/doctor-02.webp',
    email: 'jrodriguez@meditrujillo.pe',
    whatsapp: '51923456781',
    availableNow: true,
    attentionNow: true,
    featured: true,
    subscriptionStartedAt: '2026-02-15',
    subscriptionEndsAt: '2026-05-15',
    schedules: baseSchedules
  },
  {
    id: 'doc-3',
    name: 'Dra. Carmen Llanos',
    specialty: 'Pediatría',
    cmp: 'CMP 38741',
    department: 'La Libertad',
    province: 'Trujillo',
    district: 'El Porvenir',
    clinic: 'Hospital Regional Docente',
    experience: 10,
    price: 80,
    rating: 4.7,
    plan: 'pro',
    status: 'active',
    image: '/uploads/doctor-03.webp',
    photoPath: '/uploads/doctor-03.webp',
    email: 'cllanos@meditrujillo.pe',
    whatsapp: '51923456789',
    availableNow: true,
    attentionNow: true,
    featured: false,
    subscriptionStartedAt: '2026-04-10',
    subscriptionEndsAt: '2026-07-10',
    schedules: baseSchedules
  },
  {
    id: 'doc-4',
    name: 'Dr. Renzo Paredes',
    specialty: 'Traumatología',
    cmp: 'CMP 38990',
    department: 'Lima',
    province: 'Lima',
    district: 'Miraflores',
    clinic: 'OrtoVida',
    experience: 11,
    price: 90,
    rating: 4.6,
    plan: 'pro',
    status: 'active',
    image: '/uploads/doctor-01.webp',
    photoPath: '/uploads/doctor-01.webp',
    email: 'rparedes@meditrujillo.pe',
    whatsapp: '51999887766',
    availableNow: true,
    attentionNow: true,
    featured: false,
    subscriptionStartedAt: '2026-02-01',
    subscriptionEndsAt: '2026-04-30',
    schedules: baseSchedules
  },
  {
    id: 'doc-5',
    name: 'Dra. Fiorella Luna',
    specialty: 'Ginecología',
    cmp: 'CMP 45110',
    department: 'Lambayeque',
    province: 'Chiclayo',
    district: 'Chiclayo',
    clinic: 'Mujer Salud',
    experience: 14,
    price: 110,
    rating: 4.9,
    plan: 'premium',
    status: 'active',
    image: '/uploads/doctor-02.webp',
    photoPath: '/uploads/doctor-02.webp',
    email: 'fluna@meditrujillo.pe',
    whatsapp: '51944556677',
    availableNow: true,
    attentionNow: true,
    featured: true,
    subscriptionStartedAt: '2026-01-20',
    subscriptionEndsAt: '2026-04-20',
    schedules: baseSchedules
  },
  {
    id: 'doc-6',
    name: 'Lic. Camila Vera',
    specialty: 'Psicología',
    cmp: 'CPP 90218',
    department: 'La Libertad',
    province: 'Trujillo',
    district: 'Trujillo',
    clinic: 'Espacio Terapéutico Norte',
    experience: 7,
    price: 60,
    rating: 4.8,
    plan: 'pro',
    status: 'active',
    image: '/uploads/doctor-03.webp',
    photoPath: '/uploads/doctor-03.webp',
    email: 'cvera@meditrujillo.pe',
    whatsapp: '51922334455',
    availableNow: true,
    attentionNow: true,
    featured: false,
    subscriptionStartedAt: '2026-03-05',
    subscriptionEndsAt: '2026-06-05',
    schedules: baseSchedules
  }
]
